# Generated by Django 5.2.17 on 2026-09-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderdetail_price_alter_orderdetail_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('shipping', 'กำลังจัดส่ง'), ('completed', 'จัดส่งสำเร็จ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
    ]
